from snakemake.utils import min_version, validate

##### set minimum snakemake version #####
min_version("8.0.0")

#### setup #######
configfile: "config/config.yaml"
validate(config, schema="schemas/config.schema.yaml")

wildcard_constraints:
    sample="[^/]+",
    seqtype="dnaseq|rnaseq",
    nartype="DNA|RNA",
    readtype="SE|PE",
    readpair="R[12]",
    group="[^/]+",
    vartype="[^/]+",
    chr="[^/]+",
    no=r"\d+",
    rg="[^/]+",
    replicate="[^/]+",

rule all:
  input:
    expand("results/{sample}/prioritization/", 
           sample=config['data']['name'])

#### load rules ####
include: "rules/ref.smk"
include: "rules/common.smk"
include: "rules/hlatyping_prep.smk"
include: "rules/hlatyping_mhcI.smk"
include: "rules/hlatyping_mhcII.smk"
include: "rules/preproc.smk"
include: "rules/align.smk"
include: "rules/quantification.smk"
include: "rules/genefusion.smk"
include: "rules/altsplicing.smk"
include: "rules/exitron.smk"
include: "rules/indel.smk"
include: "rules/custom.smk"
include: "rules/germline.smk"
include: "rules/annotation.smk"
include: "rules/prioritization.smk"
