data:
  name:  patient2
  dnaseq: 
    #  dna_normal: ../../TESLA/melanoma/patient2/WES/TESLA_9_1.fastq.gz ../../TESLA/melanoma/patient2/WES/TESLA_9_2.fastq.gz
    #dna_tumor: ../../TESLA/melanoma/patient2/WES/TESLA_10_1.fastq.gz ../../TESLA/melanoma/patient2/WES/TESLA_10_2.fastq.gz
    dna_normal: TESLA_testdata/patient2/WES/TESLA_9_1.fastq.gz TESLA_testdata/patient2/WES/TESLA_9_2.fastq.gz
    dna_tumor: TESLA_testdata/patient2/WES/TESLA_10_1.fastq.gz TESLA_testdata/patient2/WES/TESLA_10_2.fastq.gz
  rnaseq:
    rna_tumor: ../../TESLA/melanoma/patient2/RNA/TESLA_11_1.fastq.gz ../../TESLA/melanoma/patient2/RNA/TESLA_11_2.fastq.gz
      rna_tumor: TESLA_testdata/patient2/RNA/TESLA_11_1.fastq.gz TESLA_testdata/patient2/RNA/TESLA_11_2.fastq.gz
  normal: dna_normal

### pre-processing (only applied on fastq reads)
preproc: 
  activate: true  # whether (=true) or not (=false) to include pre-processing
  minlen: 10
  quality: 20

### variant calling
# alternative splicing
altsplicing:
  activate: true # whether (=true) or not (=false) to include alternative splicing events

# exitron splicing
exitronsplicing:
  activate: true # whether (=true) or not (=false) to include exitron-splicing events

# gene fusion
genefusion:
  activate: true # whether (=true) or not (=false) to include gene fusion events






# if no readgroups file are provided 
readgroups: 


mhc:
  len_class_i: 8-11
  len_class_ii: 13-25
  



mapq: 30
chimsegmin: 20
threads: 50

ref:
  species: homo_sapiens
  release: 109
  build: GRCh38
  



### gene fusion
genefusion:
  activate: false
  vcf:

### indel
indel:
  activate: true



### snp
snp:
  activate: true
  vcf:










