refgen: testdata/GRCh38.p13.genome.fa
annotation: testdata/GRCh38_chr1.gtf  

dnaseq:
rnaseq: LNCAP_bam/G28033.LNCaP_clone_FGC.1.bam


mapq: 30
chimsegmin: 20
threads: 50

ref:
  species: homo_sapiens
  release: 109
  build: GRCh38
  

#### alternative splicing
splicing:
  activate: true   # whether (=true) or not (=false) to include splicing

#### exitron 
exitron:
  activate: true
  vcf: 

### gene fusion
genefusion:
  activate: true
  vcf:

### indel > 75bp
longindel:
  activate: true
  vcf:

### indel 
shortindel:
  activate: true
  vcf:

### snp
snp:
  activate: true
  vcf:










