name: Containerize
run-name: ${{ github.actor }} is creating a Docker container for ScanNeo2
on: [push]
  #  push:
    branches:
      #     - main
jobs:
  containerize:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        snakefile: 'workflow/Snakefile'
        task: 'containerize'
