name: Linting
run-name: ${{ github.actor }} is linting the snakemake workflow
on: [push]
jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: snakemake/snakemake-github-action@v1
        with:
          directory: '${{ github.workspace }}'
          snakefile: 'workflow/Snakefile'
          args: '--lint'

