name: Linting
run-name: ${{ github.actor }} is linting Scanneo2
on: [push]
jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pwd
      - uses: snakemake/snakemake-github-action@v1
        with:
          directory: '.tests'
          snakefile: 'workflow/Snakefile'
          args: '--lint --configfile config_basic/config.yml'

